In [1]:
import pandas as pd
import numpy as np

In [2]:
dtype = {
    "Sale": np.int32,
    "SalesAmountInEuro": np.float64,
    "Time_delay_for_conversion": np.int32,
    "click_timestamp": np.int32,
    "nb_clicks_1week": pd.Int64Dtype(),
    "product_price": np.float64,
    "product_age_group": str,
    "device_type": str,
    "audience_id": str,
    "product_gender": str,
    "product_brand": str,
    "product_category1": str,
    "product_category2": str,
    "product_category3": str,
    "product_category4": str,
    "product_category5": str,
    "product_category6": str,
    "product_category7": str,
    "product_country": str,
    "product_id": str,
    "product_title": str,
    "partner_id": str,
    "user_id": str,
}
na_values = {
    "click_timestamp": "0",
    "nb_clicks_1week": "-1",
    "product_price": "-1",
    "product_age_group": "-1",
    "device_type": "-1",
    "audience_id": "-1",
    "product_gender": "-1",
    "product_brand": "-1",
    "product_category1": "-1",
    "product_category2": "-1",
    "product_category3": "-1",
    "product_category4": "-1",
    "product_category5": "-1",
    "product_category6": "-1",
    "product_category7": "-1",
    "product_country": "-1",
    "product_id": "-1",
    "product_title": "-1",
    "partner_id": "-1",
    "user_id": "-1",
}

criteo = pd.read_csv(
    "../data/criteo/Criteo_Conversion_Search/CriteoSearchData",
    names=dtype.keys(),
    dtype=dtype,
    na_values=na_values,
    header=None,
    sep="\t",
)

In [3]:
criteo = criteo.dropna(subset=["partner_id", "user_id", "product_id"])

In [4]:
"""
0a) What is the description of the dataset?
"""
criteo.describe()

,Sale,SalesAmountInEuro,Time_delay_for_conversion,click_timestamp,nb_clicks_1week,product_price
count,1.216730e+07,1.216730e+07,1.216730e+07,1.216730e+07,9251207.0,1.216730e+07
mean,1.051584e-01,1.198982e+01,3.781205e+04,1.600548e+09,390.399443,1.133515e+01
std,3.067574e-01,9.572121e+01,2.276485e+05,2.261341e+06,1342.472732,1.205586e+02
min,0.000000e+00,-1.000000e+00,-1.000000e+00,1.596439e+09,0.0,0.000000e+00
25%,0.000000e+00,-1.000000e+00,-1.000000e+00,1.598628e+09,5.0,0.000000e+00
50%,0.000000e+00,-1.000000e+00,-1.000000e+00,1.600681e+09,37.0,0.000000e+00
75%,0.000000e+00,-1.000000e+00,-1.000000e+00,1.602489e+09,204.0,0.000000e+00
max,1.000000e+00,6.245877e+04,2.588699e+06,1.604302e+09,25390.0,7.616101e+04

In [6]:
"""
0b) What is the description of the dataset per user?
"""
criteo.groupby(["user_id"]).size().describe()

count    1.043725e+07
mean     1.165756e+00
std      6.184687e-01
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      4.240000e+02
dtype: float64

In [7]:
"""
1a) What is the description of the conversions?
"""
criteo[criteo.Sale == 1].describe()

,Sale,SalesAmountInEuro,Time_delay_for_conversion,click_timestamp,nb_clicks_1week,product_price
count,1279493.0,1.279493e+06,1.279493e+06,1.279493e+06,951362.0,1.279493e+06
mean,1.0,1.225263e+02,3.595809e+05,1.600399e+09,239.66282,1.077912e+02
std,0.0,2.710661e+02,6.140971e+05,2.255931e+06,990.883248,3.575153e+02
min,1.0,0.000000e+00,-1.000000e+00,1.596439e+09,0.0,0.000000e+00
25%,1.0,2.587189e+01,7.070000e+02,1.598493e+09,3.0,1.790000e+01
50%,1.0,5.666000e+01,7.260000e+03,1.600444e+09,22.0,4.000000e+01
75%,1.0,1.332500e+02,4.638080e+05,1.602357e+09,124.0,9.999000e+01
max,1.0,6.245877e+04,2.588699e+06,1.604302e+09,23822.0,7.616101e+04

In [8]:
"""
1b) What is the description of the conversions per user?
"""
criteo[criteo.Sale == 1].groupby(["user_id"]).size().describe()

count    1.192588e+06
mean     1.072871e+00
std      3.443121e-01
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      3.900000e+01
dtype: float64

In [9]:
"""
2a) What is the description of the impressions?
"""
criteo.loc[criteo.Sale != 1].describe()

,Sale,SalesAmountInEuro,Time_delay_for_conversion,click_timestamp,nb_clicks_1week,product_price
count,10887803.0,10887803.0,10887803.0,1.088780e+07,8299845.0,10887803.0
mean,0.0,-1.0,-1.0,1.600566e+09,407.677488,0.0
std,0.0,0.0,0.0,2.261325e+06,1375.996325,0.0
min,0.0,-1.0,-1.0,1.596439e+09,0.0,0.0
25%,0.0,-1.0,-1.0,1.598647e+09,6.0,0.0
50%,0.0,-1.0,-1.0,1.600723e+09,40.0,0.0
75%,0.0,-1.0,-1.0,1.602514e+09,216.0,0.0
max,0.0,-1.0,-1.0,1.604302e+09,25390.0,0.0

In [10]:
"""
2b) What is the description of the impressions per user?
"""
criteo.loc[criteo.Sale != 1].groupby(["user_id"]).size().describe()

count    9.495914e+06
mean     1.146578e+00
std      5.823203e-01
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      4.240000e+02
dtype: float64

In [32]:

"""
3) You have a 100% attribution rate right?
"""
num_conversions_without_impressions = criteo.loc[(criteo.Sale == 1) & (criteo.click_timestamp == -1)].shape[0]
print("100% attribution rate" if num_conversions_without_impressions == 0 else "<100% attribution rate")

100% attribution rate

In [35]:
"""
4) What is the distribution of contribution values? I know you cap them at 5 so are they mostly 5 or like 2.5 on average or what?
"""
def __compute_product_count(conversion, cap: int) -> int:
    sell_price = conversion["SalesAmountInEuro"]
    offer_price = conversion["product_price"]
    if sell_price and offer_price:
        return min(cap, sell_price // offer_price)
    elif offer_price:
        return 0
    else:
        return 1

max_purchase_counts = 5

conversions = criteo[criteo.Sale == 1]
capped_conversions = conversions.assign(
    count=conversions.apply(
        lambda conversion: __compute_product_count(
            conversion, max_purchase_counts
        ),
        axis=1,
    ),
)
capped_conversions["count"].describe()

count    1.279493e+06
mean     1.447966e+00
std      1.488017e+00
min      0.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      2.000000e+00
max      5.000000e+00
Name: count, dtype: float64

In [39]:

"""
5) you have 30 days available right?
"""
print((criteo.click_timestamp.max() - criteo.click_timestamp.min()) // (60*60*24), "days of criteo data")

90 days