In [1]:
import pandas as pd
import numpy as np

In [2]:
dtype = {
    "Sale": np.int32,
    "SalesAmountInEuro": np.float64,
    "Time_delay_for_conversion": np.int32,
    "click_timestamp": np.int32,
    "nb_clicks_1week": pd.Int64Dtype(),
    "product_price": np.float64,
    "product_age_group": str,
    "device_type": str,
    "audience_id": str,
    "product_gender": str,
    "product_brand": str,
    "product_category1": str,
    "product_category2": str,
    "product_category3": str,
    "product_category4": str,
    "product_category5": str,
    "product_category6": str,
    "product_category7": str,
    "product_country": str,
    "product_id": str,
    "product_title": str,
    "partner_id": str,
    "user_id": str,
}
na_values = {
    "click_timestamp": "0",
    "nb_clicks_1week": "-1",
    "product_price": "-1",
    "product_age_group": "-1",
    "device_type": "-1",
    "audience_id": "-1",
    "product_gender": "-1",
    "product_brand": "-1",
    "product_category1": "-1",
    "product_category2": "-1",
    "product_category3": "-1",
    "product_category4": "-1",
    "product_category5": "-1",
    "product_category6": "-1",
    "product_category7": "-1",
    "product_country": "-1",
    "product_id": "-1",
    "product_title": "-1",
    "partner_id": "-1",
    "user_id": "-1",
}

criteo = pd.read_csv(
    "../data/criteo/Criteo_Conversion_Search/CriteoSearchData",
    names=dtype.keys(),
    dtype=dtype,
    na_values=na_values,
    header=None,
    sep="\t",
)

In [3]:
criteo = criteo.dropna(subset=["partner_id", "user_id", "product_id"])

In [4]:
"""
0a) What is the description of the dataset?
"""

criteo.describe()

,Sale,SalesAmountInEuro,Time_delay_for_conversion,click_timestamp,nb_clicks_1week,product_price
count,1.216730e+07,1.216730e+07,1.216730e+07,1.216730e+07,9251207.0,1.216730e+07
mean,1.051584e-01,1.198982e+01,3.781205e+04,1.600548e+09,390.399443,1.133515e+01
std,3.067574e-01,9.572121e+01,2.276485e+05,2.261341e+06,1342.472732,1.205586e+02
min,0.000000e+00,-1.000000e+00,-1.000000e+00,1.596439e+09,0.0,0.000000e+00
25%,0.000000e+00,-1.000000e+00,-1.000000e+00,1.598628e+09,5.0,0.000000e+00
50%,0.000000e+00,-1.000000e+00,-1.000000e+00,1.600681e+09,37.0,0.000000e+00
75%,0.000000e+00,-1.000000e+00,-1.000000e+00,1.602489e+09,204.0,0.000000e+00
max,1.000000e+00,6.245877e+04,2.588699e+06,1.604302e+09,25390.0,7.616101e+04

In [5]:
"""
0b) What is the description of the dataset per user?
"""

criteo.groupby(["user_id"]).size().describe()

count    1.043725e+07
mean     1.165756e+00
std      6.184687e-01
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      4.240000e+02
dtype: float64

In [6]:
"""
1a) What is the description of the conversions?
"""

criteo[criteo.Sale == 1].describe()

,Sale,SalesAmountInEuro,Time_delay_for_conversion,click_timestamp,nb_clicks_1week,product_price
count,1279493.0,1.279493e+06,1.279493e+06,1.279493e+06,951362.0,1.279493e+06
mean,1.0,1.225263e+02,3.595809e+05,1.600399e+09,239.66282,1.077912e+02
std,0.0,2.710661e+02,6.140971e+05,2.255931e+06,990.883248,3.575153e+02
min,1.0,0.000000e+00,-1.000000e+00,1.596439e+09,0.0,0.000000e+00
25%,1.0,2.587189e+01,7.070000e+02,1.598493e+09,3.0,1.790000e+01
50%,1.0,5.666000e+01,7.260000e+03,1.600444e+09,22.0,4.000000e+01
75%,1.0,1.332500e+02,4.638080e+05,1.602357e+09,124.0,9.999000e+01
max,1.0,6.245877e+04,2.588699e+06,1.604302e+09,23822.0,7.616101e+04

In [7]:
"""
1b) What is the description of the conversions per user?
"""

criteo[criteo.Sale == 1].groupby(["user_id"]).size().describe()

count    1.192588e+06
mean     1.072871e+00
std      3.443121e-01
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      3.900000e+01
dtype: float64

In [8]:
"""
1c) What is the description of the users who convert more than once?
"""

user_conversions = criteo[criteo.Sale == 1].groupby(["user_id"]).size()
users_converting_multiple_times = user_conversions[user_conversions > 1]
users_converting_multiple_times.describe()

count    69781.000000
mean         2.245396
std          0.752219
min          2.000000
25%          2.000000
50%          2.000000
75%          2.000000
max         39.000000
dtype: float64

In [9]:
"""
1d) What is the description of the users who convert more than once by advertisers?
"""

user_advertiser_conversions = (
    criteo[criteo.Sale == 1].groupby(["user_id", "partner_id"]).size()
)
users_converting_multiple_times_by_advertiser = user_advertiser_conversions[
    user_advertiser_conversions > 1
].reset_index(name="conversion_count")
print(users_converting_multiple_times_by_advertiser.describe())
users_converting_multiple_times_by_advertiser.sort_values(
    by=["conversion_count"], ascending=False
).head(50)

       conversion_count
count      61844.000000
mean           2.237048
std            0.719252
min            2.000000
25%            2.000000
50%            2.000000
75%            2.000000
max           33.000000

,user_id,partner_id,conversion_count
11064,2DE4628E1966648A141ACA926D160E91,E3DDEB04F8AFF944B11943BB57D2F620,33
13632,3874BC72C4E8C39D4F475097F6004DCE,319A2412BDB0EF669733053640B80112,29
11550,2FED9D0F367311691498360CE6D6EE98,319A2412BDB0EF669733053640B80112,28
5531,1763D336EC150511173C0D9785493879,E3DDEB04F8AFF944B11943BB57D2F620,23
14571,3C6ED50E3B2CE4E430B8AB6F915CCEF6,E3DDEB04F8AFF944B11943BB57D2F620,23
16525,446E482E5A7472B5F045458D2F587DDD,319A2412BDB0EF669733053640B80112,23
27380,712EA806588FA01E34A6A8427E8537CC,4D4806B2F138ED89BEB51D3010AF2033,22
30147,7C8EB12D8897021A3894F1EEEB750B55,319A2412BDB0EF669733053640B80112,22
41900,AC8D778C9BF92A9CD075CFC9D1928769,5D4FE9350AF7E4CAE2CD24EDEC6F9050,17
29548,7A1114DDD7E3841696BCF39E1E011C01,925829CF82DFDC74DE3F88F003CE7BEF,17
21003,5756776212AC703766D649DB7A1B1561,1BB44E9DB5ABBD9F9A64B475291DC555,17
34138,8CD1985E9061D9FD4AA9E3EC85D42FF2,2F13BB7176EBE22D37B5AFB3C814FE12,17
37368,99EA27F61036F49A724DFA0BF08C488D,319A2412BDB0EF669733053640B80112,16
33415,8A100AA2F8C3220C4F293F2706E41067,E3DDEB04F8AFF944B11943BB57D2F620,15
26427,6D704D57A6CA6159117414268BE0B0DB,319A2412BDB0EF669733053640B80112,15
45282,BAA81D6EF36F2AC2D68013EAC50E87F2,925829CF82DFDC74DE3F88F003CE7BEF,15
53397,DC5E9D66AF6266E40BCCEDE9FFF5E4D4,319A2412BDB0EF669733053640B80112,14
26560,6DFC106016904DE6F4BEAD28AAAD4DF8,A9AD79D7E99CB08B4DA34A6B1A35557D,14
25338,6938A91480CDD287C8590D2B784BB890,319A2412BDB0EF669733053640B80112,13
34225,8D1D01D9F4C16FD5EEC8688ECB8C2BF3,319A2412BDB0EF669733053640B80112,12
49033,CA2B5FF4D9B0A1334210B01B0CFE5F64,925829CF82DFDC74DE3F88F003CE7BEF,12
33258,8965E2DB1D8A969FEA4DF05768F989DE,E3DDEB04F8AFF944B11943BB57D2F620,12
2058,08C15A6CFCE327BB1F161010472D6F92,2F13BB7176EBE22D37B5AFB3C814FE12,12
47634,C46F48847BB82D026A01EE6D715A39AC,E3DDEB04F8AFF944B11943BB57D2F620,12
2180,094962AACE4EFB62DCE780E9AE165AC2,319A2412BDB0EF669733053640B80112,12
38341,9DEC87E6F53FCB6862180BB0A5A3F595,E3DDEB04F8AFF944B11943BB57D2F620,12
19518,50F5CDC3ABB6FDFA382F7EBBC4DEF914,5D4FE9350AF7E4CAE2CD24EDEC6F9050,11
6664,1C02BAC4C6197AF08B47A50956906100,2F13BB7176EBE22D37B5AFB3C814FE12,11
21858,5AF3A8C5EA9219CF96F9A9C40015A822,E3DDEB04F8AFF944B11943BB57D2F620,11
58935,F406A5CC42B180DBE3EDFAFC038C9497,4D4806B2F138ED89BEB51D3010AF2033,11
14001,39EF5212D83FB5B787511F2B6622F7E0,E3DDEB04F8AFF944B11943BB57D2F620,11
11551,2FED9D0F367311691498360CE6D6EE98,E1703315F9986F033724DA149DC0B052,11
50987,D25345FC0DF52859075EA6492094A745,5D4FE9350AF7E4CAE2CD24EDEC6F9050,11
17806,49E432B56998B9435486E476CF04DB05,E3DDEB04F8AFF944B11943BB57D2F620,11
51121,D2EDE469E721E0FB84461A965792E5E4,1BB44E9DB5ABBD9F9A64B475291DC555,10
45573,BBD9C8482F9A209DBEFE441D72735231,ACA0099F912C66AB720E4D78A732CAF6,10
25339,6938A91480CDD287C8590D2B784BB890,E1703315F9986F033724DA149DC0B052,10
332,0179B2D46A8104523296875E6185A5D1,319A2412BDB0EF669733053640B80112,10
1908,081D0C4960628109DE9C30E39DF8C978,E3DDEB04F8AFF944B11943BB57D2F620,10
41266,A9F62C5CE7503ED35FA675C6F3B6AC05,E3DDEB04F8AFF944B11943BB57D2F620,10
12584,3441EEAF080FEBB5FA0307CEB1ABBB20,F122B91F6D102E4630817566839A4F1F,10
4868,14A51D9129B8332995F0AD2CE5B2BB38,E3DDEB04F8AFF944B11943BB57D2F620,10
37655,9B18C9FB9DA45C59E5960305A736E185,9D9E93D1D461D7BAE47FB67EC0E01B62,10
41126,A976A631FB6E831FAF36885B72D1E6BE,1BB44E9DB5ABBD9F9A64B475291DC555,10
568,026FBA79D2E30F97ADBC0E678C2305CF,2F13BB7176EBE22D37B5AFB3C814FE12,10
14987,3E2E7A41426C9773B41326F1D3CF577A,E3DDEB04F8AFF944B11943BB57D2F620,9
26058,6BE73E3E872B8CD5742540BE99366FF6,5D4FE9350AF7E4CAE2CD24EDEC6F9050,9
7721,2032495333887C1CAD9E398A5B545180,E3DDEB04F8AFF944B11943BB57D2F620,9
35748,934EBD85B72417C90970AEE2D595E01E,9D8E4D89210B822B2060852D2DD143FE,9
37312,99B20A8A4A12BC69E2D1913F0254CF98,E3DDEB04F8AFF944B11943BB57D2F620,9

In [10]:
"""
1e) What is the description of the multi-conversion rate per advertiser?
Where multi-conversion rate is
(number of users who convert more than once for an advertiser) / (number of users who convert for an advertiser)
"""

conversions = criteo[criteo.Sale == 1]
user_advertiser_conversions = conversions.groupby(["user_id", "partner_id"]).size()
multiconverters = (
    user_advertiser_conversions[user_advertiser_conversions > 1]
    .reset_index(name="multiconverter_count")
    .groupby(["partner_id"])
    .size()
    .reset_index(name="multiconverter_count")
)
converters = (
    user_advertiser_conversions.reset_index(name="converter_count")
    .groupby(["partner_id"])
    .size()
    .reset_index(name="converter_count")
)

multiconverter_rates = pd.merge(
    multiconverters, converters, how="inner", on="partner_id"
)
multiconverter_rates = (
    multiconverter_rates.assign(
        multiconverter_rate=multiconverter_rates.apply(
            lambda r: r.multiconverter_count / r.converter_count,
            axis=1,
        )
    )
    .sort_values(by=["multiconverter_rate"], ascending=False)
    .reset_index(drop=True)
)

multiconverter_rates.head(40)

,partner_id,multiconverter_count,converter_count,multiconverter_rate
0,319A2412BDB0EF669733053640B80112,2178,26280,0.082877
1,E3DDEB04F8AFF944B11943BB57D2F620,39097,477888,0.081812
2,4FE3DF46D9F3D57C872A28B9AEA876E3,384,5313,0.072276
3,E1703315F9986F033724DA149DC0B052,248,3582,0.069235
4,5D4FE9350AF7E4CAE2CD24EDEC6F9050,1102,16096,0.068464
5,F122B91F6D102E4630817566839A4F1F,2837,46732,0.060708
6,9F30550A2589106D327B2F7C829CA250,113,1918,0.058916
7,CE13C4ECD6D0EF4A9F02EB0E17B45766,2,34,0.058824
8,919377389312B4EE6C56FD94A6997C16,73,1264,0.057753
9,C6619E0137BA48395F6D230E5824A585,608,10741,0.056606
10,9D9E93D1D461D7BAE47FB67EC0E01B62,2767,52064,0.053146
11,80B621829A146066458564677C584294,208,4301,0.048361
12,74A06C6723C84E6A910A931705A832AA,619,12967,0.047737
13,BD01BAFAE73CF38C403978BBB458300C,118,2515,0.046918
14,C38B671959ACFDA46C5129405124203E,98,2129,0.046031
15,803D7F31D6B3D82E601B50CD4AA57B36,5,109,0.045872
16,743B1EE3A39E06D855A72B3B66D501D0,445,9931,0.044809
17,6BFFDE668C5BC3938C875D3D0940E699,862,19246,0.044789
18,51EBAAC05E372CBCDF0F207517A225AB,938,22103,0.042438
19,2F13BB7176EBE22D37B5AFB3C814FE12,651,15907,0.040925
20,447E3E4B29D78A9155E8C8A499F1D336,71,1735,0.040922
21,C2EDAE7C04A42370EA5A8987055C8CCA,443,10853,0.040818
22,C1D3363AF03AB33265E5D379279815B1,134,3464,0.038684
23,B85210C048A57F8A8CF4D6B851F57E56,128,3371,0.037971
24,ACA0099F912C66AB720E4D78A732CAF6,19,504,0.037698
25,4D4806B2F138ED89BEB51D3010AF2033,561,15621,0.035913
26,8D40FA754430BB410140950FCBB8FE41,3,85,0.035294
27,362124BA45449ED677E2A20FE6FE41B7,2,57,0.035088
28,4B30FD34992F339E295876B2278A14AE,84,2450,0.034286
29,E9CA69DBC2B838810A5FCED0154B6E4A,16,467,0.034261
30,DD7AAC030367C3D0E61E62D7E81C6545,4,121,0.033058
31,B4CEF05984E18752752091ED836E3E21,68,2071,0.032834
32,ED5752614DD1DE935EBFBF90C1265D9F,79,2427,0.032550
33,9946AE215D24E4E0CD9268ECB054EBC8,38,1197,0.031746
34,F0FD783189F55BAFC331AD347EAE6863,244,7706,0.031664
35,8C8BBC051B051F9424483D0ADEFAB81B,402,12932,0.031086
36,482E924BCFAA8562F60BF0BE53786C24,128,4185,0.030585
37,1EFEC54BC5B5304BA8145CCC8037F98C,1,33,0.030303
38,C72CCFD8A6E9790C5C89CEEF74F13AD2,87,2888,0.030125
39,3C5FE3370451FAB3525496A1592E6609,68,2274,0.029903

In [11]:
multiconverter_rates.sort_values(by=["converter_count"], ascending=False)

,partner_id,multiconverter_count,converter_count,multiconverter_rate
1,E3DDEB04F8AFF944B11943BB57D2F620,39097,477888,0.081812
10,9D9E93D1D461D7BAE47FB67EC0E01B62,2767,52064,0.053146
5,F122B91F6D102E4630817566839A4F1F,2837,46732,0.060708
77,9FF550C0B17A3C493378CB6E2DEEE6E4,916,45704,0.020042
0,319A2412BDB0EF669733053640B80112,2178,26280,0.082877
...,...,...,...,...
27,362124BA45449ED677E2A20FE6FE41B7,2,57,0.035088
71,1CD374F58ED161103C9A74E7EB8B4AC2,1,48,0.020833
52,968C498E6F9CA55F8C3DF73AAAC9CF86,1,41,0.024390
7,CE13C4ECD6D0EF4A9F02EB0E17B45766,2,34,0.058824
37,1EFEC54BC5B5304BA8145CCC8037F98C,1,33,0.030303

In [12]:
"""
2a) What is the description of the impressions?
"""

criteo.loc[criteo.Sale != 1].describe()

,Sale,SalesAmountInEuro,Time_delay_for_conversion,click_timestamp,nb_clicks_1week,product_price
count,10887803.0,10887803.0,10887803.0,1.088780e+07,8299845.0,10887803.0
mean,0.0,-1.0,-1.0,1.600566e+09,407.677488,0.0
std,0.0,0.0,0.0,2.261325e+06,1375.996325,0.0
min,0.0,-1.0,-1.0,1.596439e+09,0.0,0.0
25%,0.0,-1.0,-1.0,1.598647e+09,6.0,0.0
50%,0.0,-1.0,-1.0,1.600723e+09,40.0,0.0
75%,0.0,-1.0,-1.0,1.602514e+09,216.0,0.0
max,0.0,-1.0,-1.0,1.604302e+09,25390.0,0.0

In [13]:
"""
2b) What is the description of the impressions per user?
"""

criteo.loc[criteo.Sale != 1].groupby(["user_id"]).size().describe()

count    9.495914e+06
mean     1.146578e+00
std      5.823203e-01
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      4.240000e+02
dtype: float64

In [14]:
"""
3) You have a 100% attribution rate right?
"""

num_conversions_without_impressions = criteo.loc[
    (criteo.Sale == 1) & (criteo.click_timestamp == -1)
].shape[0]
print(
    "100% attribution rate"
    if num_conversions_without_impressions == 0
    else "<100% attribution rate"
)

100% attribution rate

In [15]:
"""
4) What is the distribution of contribution values after capping?
"""


def __compute_product_count(conversion, cap: int) -> int:
    sell_price = conversion["SalesAmountInEuro"]
    offer_price = conversion["product_price"]
    if sell_price and offer_price:
        return min(cap, max(1, sell_price // offer_price))
    else:
        return 1


max_purchase_counts = 5

conversions = criteo[criteo.Sale == 1]
capped_conversions = conversions.assign(
    count=conversions.apply(
        lambda conversion: __compute_product_count(conversion, max_purchase_counts),
        axis=1,
    ),
)
capped_conversions["count"].describe()

count    1.279493e+06
mean     1.680549e+00
std      1.311158e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      2.000000e+00
max      5.000000e+00
Name: count, dtype: float64

In [16]:
"""
5) you have 30 days available right?
"""

print(
    (criteo.click_timestamp.max() - criteo.click_timestamp.min()) // (60 * 60 * 24),
    "days of criteo data",
)

90 days of criteo data

In [29]:
"""
6) What is the domain size of product_category3 for these partners?
"""

x = [
    ("domain size of product_category3 for all advertisers", criteo),
    (
        "domain size of product_category3 for advertisers with converting users",
        conversions,
    ),
]

for msg, d in x:
    pc3 = d.groupby(["partner_id"]).product_category3.nunique()
    print(msg)
    print(pc3.describe())
    print("\n")

domain size of product_category3 for all advertisers
count    292.000000
mean      63.965753
std      100.010990
min        0.000000
25%        7.000000
50%       29.000000
75%       79.250000
max      809.000000
Name: product_category3, dtype: float64


domain size of product_category3 for advertisers with converting users
count    274.000000
mean      39.430657
std       68.147899
min        0.000000
25%        5.000000
50%       17.000000
75%       48.000000
max      723.000000
Name: product_category3, dtype: float64

In [30]:
big_advertiser = "E3DDEB04F8AFF944B11943BB57D2F620"

for msg, d in x:
    d = d[d.partner_id != big_advertiser]
    pc3 = d.groupby(["partner_id"]).product_category3.nunique()
    print(msg)
    print(pc3.describe())
    print("\n")

domain size of product_category3 for all advertisers
count    291.000000
mean      61.405498
std       90.089154
min        0.000000
25%        7.000000
50%       29.000000
75%       78.500000
max      667.000000
Name: product_category3, dtype: float64


domain size of product_category3 for advertisers with converting users
count    273.000000
mean      36.926740
std       54.194317
min        0.000000
25%        5.000000
50%       17.000000
75%       48.000000
max      411.000000
Name: product_category3, dtype: float64

In [31]:
"""
7) How many distinct partners/advertisers are in this dataset?
"""

x = [
    ("advertisers in the dataset", criteo),
    ("advertisers with users who have converted", conversions),
]
for msg, d in x:
    print(msg, d.partner_id.unique().shape[0])

advertisers in the dataset 292
advertisers with users who have converted 274

In [32]:
big_advertiser = "E3DDEB04F8AFF944B11943BB57D2F620"

for msg, d in x:
    d = d[d.partner_id != big_advertiser]
    print(msg, d.partner_id.unique().shape[0])

advertisers in the dataset 291
advertisers with users who have converted 273